### ISSUE TITLE
Denote components that require JS

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#158]
## Background
While the Design System's CSS Framework (fsa-style) does not provide Production-quality scripting, there are several Components that do require JS for its _UI-specific_ features to be fully realized.

**Examples:** Modal, Growl Notifications, etc.

## Task

- [x] Design a feature that clearly notes [this] component requires JS (see screenshot below).
- [x] Can it be automated via Jekyll? Perhaps a property on [`_data/navvy.yml`](https://github.com/USDA-FSA/fsa-design-system/blob/gh-pages/_data/navvy.yml) or as `page.thing` in head.
- [ ] Identify which components this applies to, e.g Modal.
  - [ ] Each identified component's docs should have some doc language that speaks to this, if only to drive home that the Design System doesn't provide Prod-quality JS for this component; but also to generally summarize the UI-oriented JS demo'd. Ideally as an `h2` on doc page (thus appearing in jump menu).

## Speculative Design

![image](https://user-images.githubusercontent.com/1165933/37676881-32ffeaf8-2c47-11e8-8092-425271ba345b.png)

**Comment by bignamehere** [comment]
@francisrupert what are your thoughts on this as a way to disclose how the JavaScript "works" in the documentation?

![image](https://user-images.githubusercontent.com/2124049/41731790-eaf1c596-7544-11e8-8339-1322bb7dbc89.png)

**Comment by francisrupert** [comment]
@bignamehere,

In our last conversation we arrived at less of a "doc structure" and more of a "here's a plain language list of what our prototype-quality JS is doing to accomplish this component's behavior."

(I'll reply again here soon after I fully form my thoughts on this).

**Comment by francisrupert** [comment]
@bignamehere,

The structure you have in that screenshot would be appropriate if we were providing true "**docs**" for _Production-quality_ scripting that we (AO UX team) authored and fully tested. 

Meanwhile, all of your content in the _Description_ column can and should be comments in the JS -- if nothing else.

I worry about presenting that structure on a component's **UI** documentation could be misinterpreted as _"this is what you **will** use, this is how this method/property/etc **will** be implemented"_; or even "_you need to replicate these exact properties/methods/etc_", when they may actually accomplish the same result with a completely different JS approach. 

For example, we scripted focus back to the originating element by passing around `data-modal-origin`, but someone else may use `document.activeElement` (which I realized some time later). What's important is the UI and behavior is implemented as prototyped and the various states of the component's HTML are consistent.

For the Design System's doc page, how much more than the below would even be necessary?
 
**Open Modal**
1. Toggle its `aria-hidden` attribute from `true` to `false`
1. Set `focus()` on the modal
1. Add `fsa-modal-scroll-fix` to `<body>`’s `classList`
1. Prevent user from focusing outside of it (aka “Keyboard Trap”).

**Close Modal**
1. Toggle its `aria-hidden` attribute from `false` to `true`
1. Set `focus()` back to element that requested the modal
1. Remove `fsa-modal-scroll-fix` from `<body>`’s `classList`

Pointing to specific lines of JS somehow is still appropriate, but I'm more interested in conveying the **what** over the **how.**

**Comment by bignamehere** [comment]
@francisrupert I worry that the documentation will be quickly out of date with any code updates that apply a slightly different approach, or any updates to the component. I question the need at all to explain in text what the User can "see" from an example. Both my example and your example seem overly verbose and hard to maintain.

**Comment by bignamehere** [comment]
@francisrupert Here is the alternative and models your example. Thoughts?

![image](https://user-images.githubusercontent.com/2124049/41745541-dfbaad32-756c-11e8-8c74-a9ea08a9bd3a.png)

**Comment by francisrupert** [comment]
@bignamehere,

It's clear we both feel it should be **straight-forward and simple**. 

>  "I worry that the documentation will be quickly out of date...."

I don't get a feeling of risk of this being a bear to maintain/update, or even getting out of date all that quickly. What **is** risky would be _"....pointing to specific lines of JS...."_ from the Markdown page. Instead, we can refer to the component's prototype-quality demo JS, something like... _"refer to [this component's] demo JS file to blah blah blah."_

> "I question the need at all to explain in text what the User can "see" from an example. "

However, not all can be _visually_ understood. This "JS Guidance" section briefly describes in plain language what UI-oriented functionality occurs - whether or not it was visually perceived. 

At any rate, I say you continue with the bullet-list approach you have going so far, and then we'll both review them before publishing.

**Comment by bignamehere** [comment]
closing as per cdc7244
