### ISSUE TITLE
508 - Update Documentation for 300 shade colors

### ISSUE THREAD

**Issue by bignamehere** [USDA-FSA/fsa-design-system#161]
There are currently 508 color contrast issues on the Design System in the Color section. 

New Color recommendations that pass WCAG AA Normal text size:

- [x] `$color-fsa-primary-300`:  `#528052`
- [x] `$color-fsa-secondary-300`:  `#5179A9`
- [x] `$color-fsa-aqua`:  `#0080A3`
- [x] `$color-fsa-red-300`:  `#E17579`  (with `$color-fsa-base` as text color)

`$color-fsa-aqua-300` passes with `$color-fsa-base` as text color

**Comment by bignamehere** [comment]
@francisrupert 

Here is another set of colors that need to be updated, but would require an FSA Style update.

Let me know your thoughts.

**Comment by francisrupert** [comment]
@bignamehere,

Very cool. I'll take these as action items in `fsa-style` repo as part of next Milestone (2.1.3). Generally speaking it comes down to subjectively playing with the tint/shade amounts attributed to each, e.g...

https://github.com/USDA-FSA/fsa-style/blob/4c01a427237618f79b3af4da0eae895acee2db69/src/stylesheets/core/_fsa.variables.scss#L23-L65

**Comment by francisrupert** [comment]
Added **BLOCKED** label as this issue awaits https://github.com/USDA-FSA/fsa-style/issues/230 being resolved and released.
