### ISSUE TITLE
DS: fsa-style@2.2.0-rc1 adjustments

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#232]
## Summary

Updating to `fsa-style@2.2.0-rc1` resulted in no breakage. Below are simple updates to be made (some of which may not have anything to do with this `fsa-style` update).

## Tasks

🔴 WAIT until `2.2.0` is released (i.e. initially BLOCKED by https://github.com/USDA-FSA/fsa-style/issues/278)

- [x] `:focus`: "Get Started" button
- [x] `:focus`: Category thumbs (outline title, not entire blob)
- [x] `:focus`: "View on GH"
- [x] Field: add "Using [foo] component" within each example (e.g. select, input, etc)
- [x] Field: add "Helpful message" to radio and check list examples
- [x] Form components: add "Within [Field](link.html)" example (e.g. `fsa-input`, etc). See [Spinbox's example](http://usda-fsa.github.io/fsa-design-system/components/spinbox/#within-a-field)
- [x] "...manipulating the HTML ~~is~~ on basic..."
- [x] Add focusable Label and Badge examples (`<a>`, `<button>`)
