### ISSUE TITLE
Mo better Growl Notification docs

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#238]
### Task 

[Growl Notification docs](http://usda-fsa.github.io/fsa-design-system/components/growl) are bit lacking, beef it up.

- [x] Better visuals, perhaps "wireframey" screenshots
- [x] Use when for each variation, e.g. _"Warning: For events that require user attention."_
- [x] Add sample notifications on load for a more blunt-force demonstration.

**Comment by francisrupert** [comment]
Reopening to add more demos.
