### ISSUE TITLE
Doc: Layout section refactor w/ new Layout components

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#324]
### Description

Previously the [Grid and Layout](http://usda-fsa.github.io/fsa-design-system/grid-and-layout/) section was purely about the Grid System. 

`fsa-style` CSS Framework now has multiple "Layout"-oriented components (http://usda-fsa.github.io/fsa-style/#layout), so the doc site's Jekyll template needs to be updated to follow the (Jekyll) template used for [Components](http://usda-fsa.github.io/fsa-design-system/components/).

### Tasks

- [x] Jekyll: `_layouts\componentsLanding.html` and `_data\navvy.yml`
- [x] Thumbnails for each
- [x] Individual issues for each new doc page
- [x] Move from `grid-and-layout` to `layout`
    - [x] Redirect from `grid-and-layout`

### Initial "Layout" components

* Box
* Divider
* Grid System
* Level
* Media Object (#314)
* Section

### Associated `fsa-style` Issues

* https://github.com/USDA-FSA/fsa-style/issues/416
* https://github.com/USDA-FSA/fsa-style/issues/385
* https://github.com/USDA-FSA/fsa-style/issues/421
* https://github.com/USDA-FSA/fsa-style/issues/419
* https://github.com/USDA-FSA/fsa-style/issues/417
* https://github.com/USDA-FSA/fsa-style/issues/418
* https://github.com/USDA-FSA/fsa-style/issues/422
* https://github.com/USDA-FSA/fsa-style/issues/406

**Comment by francisrupert** [comment]
Refactor complete. New "Layout" section ready for doc'ing. Remaining "Create Thumbnails" task moved to #337.
