### ISSUE TITLE
Doc: Slider

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#362]
### Background

* [Slider Component](https://github.com/USDA-FSA/fsa-style/issues/451) (aka `input[type=range]`) was just released in `fsa-style@2.5.2`
* Currently only viewable at https://usda-fsa.github.io/fsa-style/#component__slider

### Task

- [x] Admin
    - [x] Add to [Components Landing](http://localhost:4000/fsa-design-system/components/)
    - [x] Add thumbnail, https://usda-fsa.github.io/fsa-design-system/img/subcategories/slider.png
    - [x] Add to `_data\navvy.yml`
- [x] Doc
    - [x] Documentation Research
    - [x] Variations
    - [x] Usage
    - [x] Accessibility implications
    - [x] JavaScript Demo
    - [x] Related Resources
