### ISSUE TITLE
Behavioral Tracking - GA Updates

### ISSUE THREAD

**Issue by bignamehere** [USDA-FSA/fsa-design-system#396]
The custom events allow form more detailed and valuable data analysis with Google Analytics, so additional Design System wide enhancements should be planned and executed. Below is a list of the proposed areas of enhancement. We should attempt to hypothesize a question that can be answered with the below tracking.

- [x] Scroll Percentage
    - Should this be based on individual pages or a collective number?
    - Answers the question "Do Users scroll to XZY to read content?"
    - Instead of Percent, should it track XYZ scrolled to? Possible?
- [x] Show Code Toggle
- [x] X-Ray Toggle
- [x] Side Navigation Clicks
- [x] Code "Copy" Buttons
- [x] Related Resource Links
    - Answer the question "What else is the User interested in after reading this page?" 
- [x] On Page Links 
- [x] Github link
    - Answers the question "What content drives User to the Github site most frequently?"
- [x] Footer Links
- [ ] Videos - Find a way to track if Users watch them

**Comment by bignamehere** [comment]
Instead of tracking Scroll Percentage, tracking what the Users view on the page based on H2 text has been implemented.

**Comment by bignamehere** [comment]
Closing since all but the video tracking feature has been completed, and can be added as a new issue if video integration is used.
