### ISSUE TITLE
Create 1.18.0 branch

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#404]
Depends on https://github.com/USDA-FSA/fsa-style/issues/486

### Summary
Approach to managing documentation for `2.6.0-RC1`:

1. publish `2.6.0` as a **Release Candidate**. This gets it on NPM and ready for opt-in usage, in this case solely so we may…
1. Doc site branch w/ `fsa-style@2.6.0-RC1` dependency installed. That will be the workspace with which we completely document and make doc site updates.
1. Once fully documented, tested, and validated we bump the Release Candidate version to `2.6.0`, and publish both `fsa-style` and `fsa-design-system` in sync.

### Tasks

- [x] Branch `gh-pages` (aka `main`, `master`) to `release/1.18.0`
- [x] Install `fsa-style@2.6.0-RC1`
- [ ] Collect each of [this milestone's features](https://github.com/USDA-FSA/fsa-design-system/milestone/26) on that branch.
