### ISSUE TITLE
Publish 1.18.0

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#461]
### Summary
 
Once all tasks for [Milestone 1.18.0](https://github.com/USDA-FSA/fsa-design-system/milestone/26) are complete and ready on branch [release/1.18.0](https://github.com/USDA-FSA/fsa-design-system/tree/release/1.18.0)

### Tasks
- [x] Bump **`package.json`** version
- [x] Validate dependencies, most especially `fsa-style`
- [x] Validate all Issues in this Project/Milestone are complete and sitting on **`release/X.X.X`** branch.
- [x] Merge **`release/X.X.X`** to **`gh-pages`** (effectively master)
- [x] Test **`gh-pages`** locally
- [x] Git Tag **`gh-pages`** as version, e.g. `1.0.0`
  - [x] Push tag
  - [x] Validate on https://github.com/USDA-FSA/fsa-design-system/tags
- [x] Push **`gh-pages`**
  - [x] Validate at http://usda-fsa.github.io/fsa-design-system
- [x] Publish tag as a [Release](https://github.com/USDA-FSA/fsa-design-system/releases)
  - [x] Release Notes
- [x] Prune local and remote branches
- [x] Close 
  - [x] associated GitHub [Project](https://github.com/orgs/USDA-FSA/projects)
  - [x] associated GitHub [Milestone](https://github.com/USDA-FSA/fsa-design-system/milestones)

**Comment by francisrupert** [comment]
@bignamehere,

Published to Production: https://usda-fsa.github.io/fsa-design-system/
