### ISSUE TITLE
Analytics: Analyze and Report on doc site 

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#520]
### Background
Issue https://github.com/USDA-FSA/fsa-design-system/issues/396 implemented tracking an initial fixed set of questions to track across the doc site.

### Task

- [ ] Analyze analytics
- [ ] Answer those questions (or new questions currently answerable)
- [ ] Produce a report on findings or patterns gleaned
- [ ] Log any possible resulting actions
- [ ] What new "questions" should be implemented, e.g. track the RWD Viewer; 

### Related Issues
- #69 
- #349 
- #359 
- #396
