### ISSUE TITLE
Create Design Files

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-design-system#60]
### Task
- Create **non-code** Design Files available to download from **Get Started** section (or access if Cloud-based, e.g. Figma). 
- Dedicated repo? (ala https://github.com/18F/web-design-standards-assets).

### Primary Target: Figma
- [x] Styles: mirror each of https://usda-fsa.github.io/fsa-design-system/visual-style/
- [x] Components: mirror each of https://usda-fsa.github.io/fsa-design-system/components
- [x] Utilities: mirror each of https://usda-fsa.github.io/fsa-design-system/utilities
- [ ] Starter Templates
- [ ] Example implematations
- [ ] Available to duplicate if can't access Team Libraries

### Stretch
Nice to haves, though much of these exist in one form or another and could be a natural
- [ ] InDesign (deliverables/documentation, or possibly wireframing)
- [ ] Illustrator (lo-fi, wireframe-ish)

**Comment by francisrupert** [comment]
Effectively closed with the publication of [Alpha release of Figma Styles and Components](https://www.figma.com/community/file/994660481391659106/USDA-%7C-FPAC-Design-System)
